/**
 * Vin icon alias map.
 *
 * Maps intuitive short names to Lucide icon IDs.
 * This is pure data — no logic, no dependencies.
 */

export const iconAliases = {
  'home': 'house',
  'edit': 'square-pen',
  'unlock': 'lock-open',
  'close': 'x',
  'add': 'plus',
  'remove': 'minus',
  'delete': 'trash-2',
  'back': 'arrow-left',
  'forward': 'arrow-right',
  'up': 'arrow-up',
  'down': 'arrow-down',
  'dropdown': 'chevron-down',
  'expand': 'chevron-right',
  'collapse': 'chevron-down',
  'more': 'ellipsis',
  'dots': 'ellipsis',
  'options': 'ellipsis-vertical',
  'profile': 'user',
  'account': 'circle-user',
  'email': 'mail',
  'send': 'send',
  'attach': 'paperclip',
  'photo': 'image',
  'video': 'video',
  'audio': 'volume-2',
  'mute': 'volume-x',
  'play': 'play',
  'pause': 'pause',
  'stop': 'square',
  'next': 'skip-forward',
  'prev': 'skip-back',
  'like': 'heart',
  'favorite': 'star',
  'bookmark': 'bookmark',
  'tag': 'tag',
  'filter': 'filter',
  'sort': 'arrow-up-down',
  'refresh': 'rotate-cw',
  'sync': 'refresh-cw',
  'save': 'save',
  'copy': 'copy',
  'paste': 'clipboard',
  'cut': 'scissors',
  'undo': 'undo-2',
  'redo': 'redo-2',
  'zoom-in': 'zoom-in',
  'zoom-out': 'zoom-out',
  'fullscreen': 'maximize-2',
  'minimize': 'minimize-2',
  'pin': 'pin',
  'location': 'map-pin',
  'time': 'clock',
  'date': 'calendar',
  'notification': 'bell',
  'warning': 'triangle-alert',
  'error': 'circle-x',
  'success': 'circle-check',
  'info': 'info',
  'help': 'circle-help',
  'gear': 'settings',
  'config': 'sliders-horizontal',
  'dashboard': 'layout-dashboard',
  'list': 'list',
  'grid': 'grid-3x3',
  'table': 'table',
  'chart': 'chart-bar',
  'graph': 'chart-line',
  'pie': 'chart-pie',
  'code': 'code',
  'terminal': 'terminal',
  'bug': 'bug',
  'wifi': 'wifi',
  'bluetooth': 'bluetooth',
  'battery': 'battery',
  'power': 'power',
  'logout': 'log-out',
  'login': 'log-in',
  'signup': 'user-plus',
  'cart': 'shopping-cart',
  'bag': 'shopping-bag',
  'payment': 'credit-card',
  'receipt': 'receipt',
  'print': 'printer',
  'export': 'external-link',
  'import': 'import',
  'cloud': 'cloud',
  'database': 'database',
  'server': 'server',
  'key': 'key',
  'shield': 'shield',
  'flag': 'flag',
  'thumbs-up': 'thumbs-up',
  'thumbs-down': 'thumbs-down',
  'comment': 'message-circle',
  'chat': 'message-square',
  'reply': 'reply',
  'repost': 'repeat',
  'people': 'users',
  'team': 'users',
  'org': 'building-2',
  'company': 'building-2',
  'document': 'file-text',
  'spreadsheet': 'sheet',
  'presentation': 'projector',
  'music': 'music',
  'mic': 'mic',
  'speaker': 'volume-2',
  'headphones': 'headphones',
  'monitor': 'monitor',
  'mobile': 'smartphone',
  'tablet': 'tablet',
  'watch': 'watch',
  'lightbulb': 'lightbulb',
  'idea': 'lightbulb',
  'rocket': 'rocket',
  'sparkle': 'sparkles',
  'magic': 'wand-sparkles',
  'ai': 'brain',
  'robot': 'bot',
};

/**
 * Resolve an icon name through the alias map and icon registry.
 * @param {string} name
 * @param {Object} icons - The icons registry from icons.js
 * @returns {string|null} SVG path data or null
 */
export function resolveIcon(name, icons) {
  return icons[name] || icons[iconAliases[name]] || null;
}
